Repository pacstall/website, pull requests merged in 2023-07, with the labels that each got.

#477 feat: disable animations on prefers-reduced-motion
  client/src/components/Navigation.tsx
  client/src/components/animations/PageAnimation.tsx
  client/src/util/animation.ts
Labels: enhancement, javascript

#476 feat: load matomo only when doNotTrack allows it
  client/index.html
  client/index.production.html
Labels: enhancement, javascript, privacy

#455 Add instructions to readme, make en/es cookie consents a little better
  README.md
  client/src/locale/en-US.locale.ts
  client/src/locale/es-ES.locale.ts
Labels: documentation, localization

#443 feat(numeric-locale): add numeric locale support
  client/public/styles/global.css
  client/src/components/OneLineCodeSnippet.tsx
  client/src/components/Pagination.tsx
  client/src/components/package-details/PackageDetailsTable.tsx
  client/src/hooks/useNumericDisplay.ts
  client/src/index.tsx
  client/src/locale/HOWTO.md
  client/src/locale/en-US.locale.ts
  client/src/locale/locale.ts
  client/src/locale/numeric-systems/arabic.ts
  client/src/locale/numeric-systems/bengali.ts
  server/Makefile
Labels: enhancement, javascript, localization

#484 feat(git): shallow clones and fetches
  server/types/pac/parser/git/lib.go
Labels: enhancement, performance, go
